version = 0.1

[default.deploy.parameters]
stack_name = "yt-to-mp3-converter"
resolve_s3 = true
s3_prefix = "yt-to-mp3-converter"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
