AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Youtube Video to MP3 Converter - Static Site Template

Resources:
  ConversionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./conversion.stack.yml
      Parameters:
        VideoBucketName: !GetAtt StorageStack.Outputs.VideoBucketName
        VideoBucketArn: !GetAtt StorageStack.Outputs.VideoBucketArn
        UserConnectionsTableName: !GetAtt DatabaseStack.Outputs.UserConnectionsTableName
        UserConnectionsTableArn: !GetAtt DatabaseStack.Outputs.UserConnectionsTableArn
        VideoSourceCacheTableName: !GetAtt DatabaseStack.Outputs.VideoSourceCacheTableName
        VideoSourceCacheTableArn: !GetAtt DatabaseStack.Outputs.VideoSourceCacheTableArn

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./database.stack.yml

  FrontendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./frontend.stack.yml
      Parameters:
        VideoSourceCacheTableName: !GetAtt DatabaseStack.Outputs.VideoSourceCacheTableName
        VideoSourceCacheTableArn: !GetAtt DatabaseStack.Outputs.VideoSourceCacheTableArn
        UserConnectionsTableName: !GetAtt DatabaseStack.Outputs.UserConnectionsTableName
        UserConnectionsTableArn: !GetAtt DatabaseStack.Outputs.UserConnectionsTableArn
        ConversionWorkflow: !GetAtt DatabaseStack.Outputs.ConversionWorkflow

  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./storage.stack.yml
